env: dev
namespace: inpost
app-name: spring-boot-api

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

#config:
#  json: |
#    {
#      "key": "value"
#    }
