apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-chart.fullname" . }}-secret
  labels:
    app: {{ include "my-chart.name" . }}
stringData:
  username: {{ randAlphaNum 8 | quote }}
  password: {{ randAlphaNum 16 | quote }}
