apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.app-name .Values.env }}
  namespace: {{ .Values.namespace }}
  env: {{ .Values.env }}
spec:
  selector:
    app: {{ printf "%s-%s" .Values.app-name .Values.env }}
  ports:
  - port: 8080
    targetPort: 8080
  - port: 8081
    targetPort: 8081
  - port: 8082
    targetPort: 8082
  type: ClusterIP
