apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
    - port: 8081
      targetPort: 8081
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ include "my-chart.name" . }}
